version: "3"
services:
  web:
    image: unreliable:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5066:80"
    networks:
      - unreliablenet
networks:
  unreliablenet:
